{
 "title": "Unifi Exporter - Resource Metrics",
 "tags": [
  "UniFi",
  "Ubiquiti",
  "unifi-exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "LoadAvg",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "unifi_loadavg_1", "legendFormat": "{{name}}" },
    { "expr": "unifi_loadavg_5", "legendFormat": "{{name}}" },
    { "expr": "unifi_loadavg_15", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "unifi_mem_used / unifi_mem_total  ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Packets  IN/OUT",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(unifi_port_tx_packets_total[5m]))",
     "legendFormat": "{{name}} (TX)"
    },
    {
     "expr": "- sum by (name) (rate(unifi_port_rx_packets_total[5m]))",
     "legendFormat": "{{name}} (RX)"
    }
   ]
  }
 ]
}