{
 "title": "Unifi Exporter - Device Metrics",
 "description": "Device Metrics by device name  (UniFi-Exporter  https://github.com/c0psrul3/unifi-exporter)",
 "tags": [
  "UniFi",
  "Ubiquiti",
  "unifi-exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(unifi_device_info{},unifi_controller)"
    }
   },
   {
    "name": "site",
    "label": "Site",
    "query": {
     "query": "label_values(unifi_device_info{},unifi_default_site)"
    }
   },
   {
    "name": "name",
    "label": "Device name",
    "query": {
     "query": "label_values(unifi_device_info{unifi_controller=~\"$controller\",unifi_default_site=~\"$site\"},name)"
    }
   },
   {
    "name": "model",
    "label": "Model",
    "query": {
     "query": "label_values(unifi_device_info{name=~\"$name\"},model)"
    }
   },
   {
    "name": "type",
    "label": "Type",
    "query": {
     "query": "label_values(unifi_device_info{name=~\"$name\",model=~\"$model\"},type)"
    }
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(unifi_device_info{name=~\"$name\"},hostname)"
    }
   },
   {
    "name": "mac",
    "label": "MAC",
    "query": {
     "query": "label_values(unifi_device_info{name=~\"$name\"},mac)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$hostname   ($name)",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "node",
   "options": {
    "content": "<table style=\"font-size: 135%;\">\n<tr>\n<td style=\"text-align: center;\">Name</td>\n<td style=\"text-align: center;\">Hostname</td>\n</tr>\n<tr>\n<td>$name</td>\n<td>$hostname</td>\n</tr>\n</table>"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unifi_device_uptime{name=~\"[[name]]\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "LoadAvg（5m）",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unifi_loadavg_5{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(unifi_mem_used{name=~\"$name\"} / unifi_mem_total{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Number Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg by (name) (unifi_vap_num_sta{name=~\"$name\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Uplink (packets)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(avg(rate(unifi_uplink_tx_packets_total{name=~\"$name\"}[$interval])) by (name))",
     "legendFormat": "TX"
    },
    {
     "expr": "(avg(rate(unifi_uplink_rx_packets_total{name=~\"$name\"}[$interval])) by (name))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Uplink (data)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(avg(rate(unifi_uplink_tx_bytes_total{name=~\"$name\"}[$interval])) by (name))",
     "legendFormat": "TX"
    },
    {
     "expr": "(avg(rate(unifi_uplink_rx_bytes_total{name=~\"$name\"}[$interval])) by (name))",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "PoE Energy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (avg_over_time(unifi_port_poe_current{name=~\"$name\"}[$interval])) without (port)",
     "legendFormat": "Current"
    },
    {
     "expr": "avg (avg_over_time(unifi_port_poe_voltage{name=~\"$name\"}[$interval])) without (port)",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Last Seen",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unifi_device_last_seen{name=~\"[[name]]\"} * 1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(unifi_mem_used{name=~\"$name\"} / unifi_mem_total{name=~\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "LoadAvg（5m）",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "unifi_loadavg_1{name=~\"$name\"}",
       "legendFormat": "{{name}} (1m)"
      },
      {
       "expr": "unifi_loadavg_5{name=~\"$name\"}",
       "legendFormat": "{{name}} (5m)"
      },
      {
       "expr": "unifi_loadavg_15{name=~\"$name\"}",
       "legendFormat": "{{name}} (15m)"
      }
     ]
    }
   ]
  },
  { "title": "Wireless", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Number of Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "unifi_vap_num_sta{name=~\"$name\"}",
     "legendFormat": "{{name}} ({{radio}}ghz)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Uplink Data (TX/RX)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "- (avg(rate(unifi_uplink_rx_bytes_total{name=~\"$name\"}[$interval])) by (name,hostname,ip_address,mac))",
     "legendFormat": "{{name}} (RX)"
    },
    {
     "expr": "avg(rate(unifi_uplink_tx_bytes_total{name=~\"$name\"}[$interval])) by (name,hostname,ip_address,mac)",
     "legendFormat": "{{name}} (TX)"
    }
   ]
  },
  {
   "title": "PoE Current by Port",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(unifi_port_poe_power{name=~\"$name\"}[$interval])",
     "legendFormat": "Port {{port}}"
    }
   ]
  },
  {
   "title": "PoE Current by Port",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "mamph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(unifi_port_poe_current{name=~\"$name\"}[$interval])",
     "legendFormat": "Port {{port}}"
    }
   ]
  },
  {
   "title": "PoE Voltage by Port",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 21, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(unifi_port_poe_voltage{name=~\"$name\"}[$interval])",
     "legendFormat": "Port {{port}}"
    }
   ]
  },
  {
   "title": "Uplink Packets  (TX/RX)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (name,hostname,ip_address,mac) (rate(unifi_uplink_tx_packets_total{name=~\"$name\"}[$interval]))",
     "legendFormat": "{{name}} (TX)"
    },
    {
     "expr": "- sum by (name,hostname,ip_address,mac) (rate(unifi_uplink_rx_packets_total{name=~\"$name\"}[$interval]))",
     "legendFormat": "{{name}} (RX)"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bps", "label": "Upload (-) / Download（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{name=~'$name',device!~'tap.*'}[$interval])*8",
     "legendFormat": "{{device}}_in download"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{name=~'$name',device!~'tap.*'}[$interval])*8",
     "legendFormat": "{{device}}_out upload"
    }
   ]
  },
  {
   "title": "Maximum partition ($maxmount) usage",
   "type": "singlestat",
   "description": "Get the largest partition by the variable maxmount. ",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 31 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{name=~\"$name\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {name=~\"$name\",mountpoint=\"$maxmount\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "General temperature",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "expr": "unifi_general_temperature{name=~\"$name\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}