from . import device

class US8P150(device.Device):

    def __init__(self, site, data):
        super(US8P150, self).__init__(site, data)

        self.port = {}
        self.parse_stat(data['stat'])
        self.parse_uplink(data.get('uplink'))
        self.parse_port_table(data['port_table'])
        self.general_temperature = data.get('general_temperature')
        self.parse_sysstat(data.get('sys_stats'))

    def parse_port_table(self, data):
        for port in data:
            self.port[port['port_idx']] = port

# {
#     "_id": "58556a4fb410cf6b940e570a",
#     "_uptime": 3641077,
#     "adopted": true,
#     "bytes": 0,
#     "cfgversion": "3280a08c720ca056",
#     "config_network": {
#         "ip": "192.168.1.226",
#         "type": "dhcp"
#     },
#     "connect_request_ip": "192.168.1.226",
#     "connect_request_port": "40880",
#     "considered_lost_at": 1485632663,
#     "device_id": "58556a4fb410cf6b940e570a",
#     "dhcp_server_table": [],
#     "dot1x_dyvlan_enabled": false,
#     "dot1x_portctrl_enabled": false,
#     "downlink_table": [
#         {
#             "full_duplex": true,
#             "mac": "44:d9:e7:f6:9f:99",
#             "port_idx": 5,
#             "speed": 1000
#         }
#     ],
#     "ethernet_table": [
#         {
#             "mac": "f0:9f:c2:0a:4a:ca",
#             "name": "eth0",
#             "num_port": 10
#         },
#         {
#             "mac": "f0:9f:c2:0a:4a:cb",
#             "name": "srv0"
#         }
#     ],
#     "flowctrl_enabled": false,
#     "fw_caps": 0,
#     "general_temperature": 63,
#     "guest-num_sta": 0,
#     "has_fan": false,
#     "inform_authkey": "...",
#     "inform_ip": "192.168.1.3",
#     "inform_url": "http://192.168.1.3:8080/inform",
#     "ip": "192.168.1.226",
#     "jumboframe_enabled": false,
#     "known_cfgversion": "3280a08c720ca056",
#     "last_seen": 1485632591,
#     "locating": false,
#     "mac": "f0:9f:c2:0a:4a:ca",
#     "model": "US8P150",
#     "name": "switch-trappen",
#     "next_heartbeat_at": 1485632615,
#     "num_sta": 22,
#     "overheating": false,
#     "port_table": [
#         {
#             "aggregated_by": false,
#             "autoneg": true,
#             "bytes-r": 0,
#             "enable": true,
#             "flowctrl_rx": false,
#             "flowctrl_tx": false,
#             "full_duplex": false,
#             "is_uplink": false,
#             "jumbo": false,
#             "masked": false,
#             "media": "GE",
#             "name": "Port 1",
#             "op_mode": "switch",
#             "poe_class": "Unknown",
#             "poe_current": "0.00",
#             "poe_enable": false,
#             "poe_good": false,
#             "poe_mode": "auto",
#             "poe_power": "0.00",
#             "poe_voltage": "0.00",
#             "port_idx": 1,
#             "port_poe": true,
#             "portconf_id": "56c87bd0b41038d25762ce8f",
#             "rx_broadcast": 0,
#             "rx_bytes": 0,
#             "rx_bytes-r": 0,
#             "rx_dropped": 0,
#             "rx_errors": 0,
#             "rx_multicast": 0,
#             "rx_packets": 0,
#             "speed": 0,
#             "stp_pathcost": 0,
#             "stp_state": "disabled",
#             "tx_broadcast": 0,
#             "tx_bytes": 0,
#             "tx_bytes-r": 0,
#             "tx_dropped": 0,
#             "tx_errors": 0,
#             "tx_multicast": 0,
#             "tx_packets": 0,
#             "up": false
#         },
#         {
#             "aggregated_by": false,
#             "autoneg": true,
#             "bytes-r": 0,
#             "enable": true,
#             "flowctrl_rx": false,
#             "flowctrl_tx": false,
#             "full_duplex": false,
#             "is_uplink": false,
#             "jumbo": false,
#             "masked": false,
#             "media": "GE",
#             "name": "Port 2",
#             "op_mode": "switch",
#             "poe_class": "Unknown",
#             "poe_current": "0.00",
#             "poe_enable": false,
#             "poe_good": false,
#             "poe_mode": "auto",
#             "poe_power": "0.00",
#             "poe_voltage": "0.00",
#             "port_idx": 2,
#             "port_poe": true,
#             "portconf_id": "56c87bd0b41038d25762ce8f",
#             "rx_broadcast": 0,
#             "rx_bytes": 0,
#             "rx_bytes-r": 0,
#             "rx_dropped": 0,
#             "rx_errors": 0,
#             "rx_multicast": 0,
#             "rx_packets": 0,
#             "speed": 0,
#             "stp_pathcost": 0,
#             "stp_state": "disabled",
#             "tx_broadcast": 0,
#             "tx_bytes": 0,
#             "tx_bytes-r": 0,
#             "tx_dropped": 0,
#             "tx_errors": 0,
#             "tx_multicast": 0,
#             "tx_packets": 0,
#             "up": false
#         },
#         {
#             "aggregated_by": false,
#             "autoneg": true,
#             "bytes-r": 0,
#             "enable": true,
#             "flowctrl_rx": false,
#             "flowctrl_tx": false,
#             "full_duplex": false,
#             "is_uplink": false,
#             "jumbo": false,
#             "masked": false,
#             "media": "GE",
#             "name": "Port 3",
#             "op_mode": "switch",
#             "poe_class": "Unknown",
#             "poe_current": "0.00",
#             "poe_enable": false,
#             "poe_good": false,
#             "poe_mode": "auto",
#             "poe_power": "0.00",
#             "poe_voltage": "0.00",
#             "port_idx": 3,
#             "port_poe": true,
#             "portconf_id": "56c87bd0b41038d25762ce8f",
#             "rx_broadcast": 0,
#             "rx_bytes": 0,
#             "rx_bytes-r": 0,
#             "rx_dropped": 0,
#             "rx_errors": 0,
#             "rx_multicast": 0,
#             "rx_packets": 0,
#             "speed": 0,
#             "stp_pathcost": 0,
#             "stp_state": "disabled",
#             "tx_broadcast": 0,
#             "tx_bytes": 0,
#             "tx_bytes-r": 0,
#             "tx_dropped": 0,
#             "tx_errors": 0,
#             "tx_multicast": 0,
#             "tx_packets": 0,
#             "up": false
#         },
#         {
#             "aggregated_by": false,
#             "autoneg": true,
#             "bytes-r": 0,
#             "enable": true,
#             "flowctrl_rx": false,
#             "flowctrl_tx": false,
#             "full_duplex": false,
#             "is_uplink": false,
#             "jumbo": false,
#             "masked": false,
#             "media": "GE",
#             "name": "Port 4",
#             "op_mode": "switch",
#             "poe_class": "Unknown",
#             "poe_current": "0.00",
#             "poe_enable": false,
#             "poe_good": false,
#             "poe_mode": "auto",
#             "poe_power": "0.00",
#             "poe_voltage": "0.00",
#             "port_idx": 4,
#             "port_poe": true,
#             "portconf_id": "56c87bd0b41038d25762ce8f",
#             "rx_broadcast": 0,
#             "rx_bytes": 0,
#             "rx_bytes-r": 0,
#             "rx_dropped": 0,
#             "rx_errors": 0,
#             "rx_multicast": 0,
#             "rx_packets": 0,
#             "speed": 0,
#             "stp_pathcost": 0,
#             "stp_state": "disabled",
#             "tx_broadcast": 0,
#             "tx_bytes": 0,
#             "tx_bytes-r": 0,
#             "tx_dropped": 0,
#             "tx_errors": 0,
#             "tx_multicast": 0,
#             "tx_packets": 0,
#             "up": false
#         },
#         {
#             "aggregated_by": false,
#             "autoneg": true,
#             "bytes-r": 11826,
#             "enable": true,
#             "flowctrl_rx": false,
#             "flowctrl_tx": false,
#             "full_duplex": true,
#             "is_uplink": false,
#             "jumbo": false,
#             "masked": false,
#             "media": "GE",
#             "name": "Port 5",
#             "op_mode": "switch",
#             "poe_class": "Class 0",
#             "poe_current": "77.75",
#             "poe_enable": true,
#             "poe_good": true,
#             "poe_mode": "auto",
#             "poe_power": "4.16",
#             "poe_voltage": "53.46",
#             "port_idx": 5,
#             "port_poe": true,
#             "portconf_id": "56c87bd0b41038d25762ce8f",
#             "rx_broadcast": 1965275,
#             "rx_bytes": 176744755020,
#             "rx_bytes-r": 4496,
#             "rx_dropped": 0,
#             "rx_errors": 0,
#             "rx_multicast": 1843103,
#             "rx_packets": 311222635,
#             "speed": 1000,
#             "stp_pathcost": 20000,
#             "stp_state": "forwarding",
#             "tx_broadcast": 1843267,
#             "tx_bytes": 539674069439,
#             "tx_bytes-r": 7329,
#             "tx_dropped": 0,
#             "tx_errors": 0,
#             "tx_multicast": 2621212,
#             "tx_packets": 441936297,
#             "up": true
#         },
#         {
#             "aggregated_by": false,
#             "autoneg": true,
#             "bytes-r": 13448,
#             "enable": true,
#             "flowctrl_rx": false,
#             "flowctrl_tx": false,
#             "full_duplex": true,
#             "is_uplink": false,
#             "jumbo": false,
#             "masked": false,
#             "media": "GE",
#             "name": "Port 6",
#             "op_mode": "switch",
#             "poe_class": "Unknown",
#             "poe_current": "0.00",
#             "poe_enable": false,
#             "poe_good": false,
#             "poe_mode": "auto",
#             "poe_power": "0.00",
#             "poe_voltage": "0.00",
#             "port_idx": 6,
#             "port_poe": true,
#             "portconf_id": "56c87bd0b41038d25762ce8f",
#             "rx_broadcast": 1580314,
#             "rx_bytes": 178970189461,
#             "rx_bytes-r": 6930,
#             "rx_dropped": 0,
#             "rx_errors": 0,
#             "rx_multicast": 681287,
#             "rx_packets": 229507948,
#             "speed": 1000,
#             "stp_pathcost": 20000,
#             "stp_state": "forwarding",
#             "tx_broadcast": 2228229,
#             "tx_bytes": 230673614216,
#             "tx_bytes-r": 6518,
#             "tx_dropped": 0,
#             "tx_errors": 0,
#             "tx_multicast": 3783026,
#             "tx_packets": 260146954,
#             "up": true
#         },
#         {
#             "aggregated_by": false,
#             "autoneg": true,
#             "bytes-r": 385,
#             "enable": true,
#             "flowctrl_rx": false,
#             "flowctrl_tx": false,
#             "full_duplex": true,
#             "is_uplink": false,
#             "jumbo": false,
#             "masked": false,
#             "media": "GE",
#             "name": "Port 7",
#             "op_mode": "switch",
#             "poe_class": "Unknown",
#             "poe_current": "0.00",
#             "poe_enable": false,
#             "poe_good": false,
#             "poe_mode": "auto",
#             "poe_power": "0.00",
#             "poe_voltage": "0.00",
#             "port_idx": 7,
#             "port_poe": true,
#             "portconf_id": "56c87bd0b41038d25762ce8f",
#             "rx_broadcast": 12,
#             "rx_bytes": 6803927,
#             "rx_bytes-r": 4,
#             "rx_dropped": 0,
#             "rx_errors": 0,
#             "rx_multicast": 0,
#             "rx_packets": 82298,
#             "speed": 100,
#             "stp_pathcost": 200000,
#             "stp_state": "forwarding",
#             "tx_broadcast": 3808531,
#             "tx_bytes": 1054811281,
#             "tx_bytes-r": 380,
#             "tx_dropped": 0,
#             "tx_errors": 0,
#             "tx_multicast": 4464313,
#             "tx_packets": 8378604,
#             "up": true
#         },
#         {
#             "aggregated_by": false,
#             "autoneg": true,
#             "bytes-r": 4256,
#             "enable": true,
#             "flowctrl_rx": false,
#             "flowctrl_tx": false,
#             "full_duplex": true,
#             "is_uplink": true,
#             "jumbo": false,
#             "masked": false,
#             "media": "GE",
#             "name": "Port 8",
#             "op_mode": "switch",
#             "poe_class": "Unknown",
#             "poe_current": "0.00",
#             "poe_enable": false,
#             "poe_good": false,
#             "poe_mode": "auto",
#             "poe_power": "0.00",
#             "poe_voltage": "0.00",
#             "port_idx": 8,
#             "port_poe": true,
#             "portconf_id": "56c87bd0b41038d25762ce8f",
#             "rx_broadcast": 146507,
#             "rx_bytes": 478603665596,
#             "rx_bytes-r": 3057,
#             "rx_dropped": 0,
#             "rx_errors": 0,
#             "rx_multicast": 0,
#             "rx_packets": 380556410,
#             "speed": 1000,
#             "stp_pathcost": 20000,
#             "stp_state": "forwarding",
#             "tx_broadcast": 3662034,
#             "tx_bytes": 65698353872,
#             "tx_bytes-r": 1199,
#             "tx_dropped": 0,
#             "tx_errors": 0,
#             "tx_multicast": 4464311,
#             "tx_packets": 231549589,
#             "up": true
#         },
#         {
#             "aggregated_by": false,
#             "autoneg": true,
#             "bytes-r": 0,
#             "enable": true,
#             "flowctrl_rx": false,
#             "flowctrl_tx": false,
#             "full_duplex": false,
#             "is_uplink": false,
#             "jumbo": false,
#             "masked": false,
#             "media": "SFP",
#             "name": "SFP 1",
#             "op_mode": "switch",
#             "port_idx": 9,
#             "port_poe": false,
#             "portconf_id": "56c87bd0b41038d25762ce8f",
#             "rx_broadcast": 0,
#             "rx_bytes": 0,
#             "rx_bytes-r": 0,
#             "rx_dropped": 0,
#             "rx_errors": 0,
#             "rx_multicast": 0,
#             "rx_packets": 0,
#             "sfp_found": false,
#             "speed": 0,
#             "stp_pathcost": 0,
#             "stp_state": "disabled",
#             "tx_broadcast": 0,
#             "tx_bytes": 0,
#             "tx_bytes-r": 0,
#             "tx_dropped": 0,
#             "tx_errors": 0,
#             "tx_multicast": 0,
#             "tx_packets": 0,
#             "up": false
#         },
#         {
#             "aggregated_by": false,
#             "autoneg": true,
#             "bytes-r": 0,
#             "enable": true,
#             "flowctrl_rx": false,
#             "flowctrl_tx": false,
#             "full_duplex": false,
#             "is_uplink": false,
#             "jumbo": false,
#             "masked": false,
#             "media": "SFP",
#             "name": "SFP 2",
#             "op_mode": "switch",
#             "port_idx": 10,
#             "port_poe": false,
#             "portconf_id": "56c87bd0b41038d25762ce8f",
#             "rx_broadcast": 0,
#             "rx_bytes": 0,
#             "rx_bytes-r": 0,
#             "rx_dropped": 0,
#             "rx_errors": 0,
#             "rx_multicast": 0,
#             "rx_packets": 0,
#             "sfp_found": false,
#             "speed": 0,
#             "stp_pathcost": 0,
#             "stp_state": "disabled",
#             "tx_broadcast": 0,
#             "tx_bytes": 0,
#             "tx_bytes-r": 0,
#             "tx_dropped": 0,
#             "tx_errors": 0,
#             "tx_multicast": 0,
#             "tx_packets": 0,
#             "up": false
#         }
#     ],
#     "rx_bytes": 65698353872,
#     "serial": "F09FC20A4ACA",
#     "site_id": "56c87bc1b41038d25762ce86",
#     "stat": {
#         "mac": "f0:9f:c2:0a:4a:ca",
#         "port_5-rx_bytes": 174998957475,
#         "port_5-rx_packets": 301949064,
#         "port_5-tx_bytes": 520122521522,
#         "port_5-tx_packets": 427159453,
#         "port_6-rx_bytes": 166842488635,
#         "port_6-rx_packets": 219854631,
#         "port_6-tx_bytes": 229212375520,
#         "port_6-tx_packets": 254220128,
#         "port_7-rx_bytes": 6621976,
#         "port_7-rx_packets": 80125,
#         "port_7-tx_bytes": 1025174082,
#         "port_7-tx_packets": 8145657,
#         "port_8-rx_bytes": 469223202436,
#         "port_8-rx_packets": 372402600,
#         "port_8-tx_bytes": 63409333653,
#         "port_8-tx_packets": 224828560,
#         "rx_bytes": 811071270522,
#         "rx_packets": 894286420,
#         "tx_bytes": 813769404777,
#         "tx_packets": 914353798,
#         "uplink-rx_bytes": 488790756975,
#         "uplink-rx_packets": 389433418,
#         "uplink-tx_bytes": 69186801149,
#         "uplink-tx_packets": 238979784
#     },
#     "state": 1,
#     "stp_priority": "32768",
#     "stp_version": "rstp",
#     "tx_bytes": 478603665596,
#     "type": "usw",
#     "upgradable": true,
#     "uplink": {
#         "full_duplex": true,
#         "ip": "192.168.1.226",
#         "mac": "f0:9f:c2:0a:4a:ca",
#         "max_speed": 1000,
#         "media": "GE",
#         "name": "eth0",
#         "netmask": "255.255.255.0",
#         "num_port": 10,
#         "port_idx": 8,
#         "rx_bytes": 478603665596,
#         "rx_bytes-r": 3057,
#         "rx_dropped": 0,
#         "rx_errors": 0,
#         "rx_multicast": 0,
#         "rx_packets": 380556410,
#         "speed": 1000,
#         "tx_bytes": 65698353872,
#         "tx_bytes-r": 1199,
#         "tx_dropped": 0,
#         "tx_errors": 0,
#         "tx_packets": 231549589,
#         "type": "wire",
#         "up": true
#     },
#     "uplink_depth": 1,
#     "uptime": 3641077,
#     "user-num_sta": 22,
#     "version": "3.3.12.3861",
#     "x_authkey": "...",
#     "x_fingerprint": "70:b5:2e:d2:ec:59:6d:18:fb:11:12:d9:cb:8d:8f:74"
# }
